version: "3"

server:
  command: "php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8080 --workers=auto --max-requests=1000 --rpc-port=6001"
  relay: pipes

http:
  address: "0.0.0.0:8080"
  middleware:
    - gzip
    - static
  static:
    dir: "/var/www/html/public"
    forbid:
      - ".php"
      - ".htaccess"
    response:
      X-Request-ID: ""
  pool:
    num_workers: 0
    max_jobs: 1000
    allocate_timeout: 60s
    destroy_timeout: 60s
    supervisor:
      max_worker_memory: 128

logs:
  mode: production
  level: warn
  encoding: json
  output: stderr

status:
  address: "0.0.0.0:2114"

reload:
  interval: 1s
  patterns: [".php"]
  services:
    http:
      recursive: true
      dirs: ["/var/www/html"]
